# copyright: 2022 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_olci
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::shapely
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::ipywidgets
  - conda-forge::jupyter_nbextensions_configurator
  - conda-forge::scikit-image
  - conda-forge::bokeh
  - conda-forge::ipykernel
  - conda-forge::cmocean
  - cmts::hda=1.1
  - cmts::eumartools
  - eumetsat-forge::eumdac

