name: cmts_learn_olci
channels:
  - conda-forge
  - cmts
dependencies:
  - python=3.8
  - notebook
  - eumdac
  - hda
  - xarray
  - netcdf4
  - shapely
  - matplotlib
  - cartopy
  - jupyter_contrib_nbextensions
  - eumartools
